### PR TITLE
Add json (un)marshaling support (fixes #44)

### LINKED ISSUE #44: support json marshaller
hi,

currently semver.Version does not support json (un)marshal interfaces.

When json encoded, it results in an empty string. 
I suspect it happens because the struct won 't export any public fields.

See the demo code to work around this, alternatively,

```
package main

import (
	"encoding/json"
	"fmt"

	"github.com/Masterminds/semver"
)

type Jversion struct {
	*semver.Version
}

func NewJversion(s string) (*Jversion, error) {
	v, err := semver.NewVersion(s)
	if err != nil {
		return nil, err
	}
	return &Jversion{Version: v}, nil
}

func (a *Jversion) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	v, err := semver.NewVersion(s)
	if err != nil {
		return err
	}
	a.Version = v
	return nil
}

func (a *Jversion) MarshalJSON() ([]byte, error) {
	return json.Marshal(a.String())
}

func main() {
	s, err := NewJversion("0.0.1")
	kk(err)
	b, err2 := json.Marshal(s)
	kk(err2)
	fmt.Println(string(b))
}

func kk(err error) {
	if err != nil {
		panic(err)
	}
}
```

### PR DESCRIPTION
**Pull request by mh-cbon**

### CODE REVIEW

**Comment by mh-cbon** [comment]
@mattfarina @sdboyer  build on 1.5 failed for some reasons :x

check https://travis-ci.org/Masterminds/semver/jobs/210619978

I can t relaunch the build to see if that would fix the problem.

```sh
# github.com/golang/lint

../../../gopkg.in/alecthomas/gometalinter.v1/vendor/src/github.com/golang/lint/lint.go:250: undefined: types.ImportMode

WARNING: failed to install one or more linters: exit status 2 (installing individually)

# github.com/golang/lint

../../../gopkg.in/alecthomas/gometalinter.v1/vendor/src/github.com/golang/lint/lint.go:250: undefined: types.ImportMode

WARNING: failed to install github.com/golang/lint/golint: exit status 2

gometalinter.v1: error: failed to install the following linters: github.com/golang/lint/golint

make: *** [setup] Error 1

The command "GO15VENDOREXPERIMENT=1 make setup" exited with 2.
```

**Comment by mh-cbon** [comment]
@mattfarina  not merged ?

**Comment by mattfarina** [comment]
@mh-cbon Thanks for the contribution!

**Comment by mh-cbon** [comment]
thanks for handling!
